// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shiujxbvzhcgtaejcxja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaXVqeGJ2emhjZ3RhZWpjeGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1Mzc0NDksImV4cCI6MjA1NTExMzQ0OX0.XXdH3BNa0yVIcRS7adKvi7H-m24Je-2Vq6D2yPp7K_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);